### ISSUE TITLE
Rust项目使用SM9算法

### ISSUE THREAD

**Issue by asyncwhale** [MaxKingPor/libgmssl-sys#1]
嗨，请问在rust项目中可以通过这个包来使用sm9算法吗

**Comment by asyncwhale** [comment]
有使用demo或者文档不

**Comment by MaxKingPor** [comment]
> 
这个库这是一个快速链接[GmSSL 3.1.0](https://github.com/guanzhi/GmSSL)是支持sm9的 目前并没有文档或者Demo

**Comment by MaxKingPor** [comment]
> > 
> 
> 这个库这是一个快速链接[GmSSL 3.1.0](https://github.com/guanzhi/GmSSL)是支持sm9的 目前并没有文档或者Demo

可以参考这个[sm9.h](https://github.com/MaxKingPor/libgmssl-sys/blob/master/GmSSL/include/gmssl/sm9.h)
[c Demo](https://github.com/MaxKingPor/libgmssl-sys/tree/master/GmSSL/demos/src)

**Comment by asyncwhale** [comment]
好嘞，太感谢了，在rust中找了好多gm库都不支持sm9，我在rust中试下

**Comment by asyncwhale** [comment]
大佬，还是请教下这个包应该怎么用呀，我放到工程中的toml文件中，在单测中使用包里面的方法编译不过诶

**Comment by MaxKingPor** [comment]
> 大佬，还是请教下这个包应该怎么用呀，我放到工程中的toml文件中，在单测中使用包里面的方法编译不过诶

看看你的Cargo.toml

**Comment by asyncwhale** [comment]
我只是加了一个这个依赖
[dependencies]
libgmssl-sys = "3.1.0"
因为是初学rust，所以不清楚是不是还漏了啥别的，toml加了后，我就直接在单测中运行
#[cfg(test)]
mod tests {
    use libgmssl_sys::sm2_key_generate;

    #[test]
    fn test_sm2_gen() {
        unsafe {
            let mut key = std::mem::MaybeUninit::uninit();
            let r = sm2_key_generate(key.as_mut_ptr());
            assert_eq!(r, 1);
            let key = key.assume_init();
            println!("SM2_KEY: {key:?}")
        }
    }
}
然后失败了

**Comment by MaxKingPor** [comment]
> 我只是加了一个这个依赖 [dependencies] libgmssl-sys = "3.1.0" 因为是初学rust，所以不清楚是不是还漏了啥别的，toml加了后，我就直接在单测中运行 #[cfg(test)] mod tests { use libgmssl_sys::sm2_key_generate;
> 
> ```
> #[test]
> fn test_sm2_gen() {
>     unsafe {
>         let mut key = std::mem::MaybeUninit::uninit();
>         let r = sm2_key_generate(key.as_mut_ptr());
>         assert_eq!(r, 1);
>         let key = key.assume_init();
>         println!("SM2_KEY: {key:?}")
>     }
> }
> ```
> 
> } 然后失败了

cmake 安装没有 还需要c编译环境

**Comment by asyncwhale** [comment]
> > 我只是加了一个这个依赖 [dependencies] libgmssl-sys = "3.1.0" 因为是初学rust，所以不清楚是不是还漏了啥别的，toml加了后，我就直接在单测中运行 #[cfg(test)] mod tests { use libgmssl_sys::sm2_key_generate;
> > ```
> > #[test]
> > fn test_sm2_gen() {
> >     unsafe {
> >         let mut key = std::mem::MaybeUninit::uninit();
> >         let r = sm2_key_generate(key.as_mut_ptr());
> >         assert_eq!(r, 1);
> >         let key = key.assume_init();
> >         println!("SM2_KEY: {key:?}")
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > } 然后失败了
> 
> cmake 安装没有 还需要c编译环境

我刚刚确认了下已经装上啦，后面应该怎么做呀=。=

**Comment by asyncwhale** [comment]
我大概理解你的意思啦，这个报错你有见过吗
![image](https://github.com/MaxKingPor/libgmssl-sys/assets/58063712/753d7afe-d0e6-4a89-af3b-8eefe05776d1)

**Comment by MaxKingPor** [comment]
> 我大概理解你的意思啦，这个报错你有见过吗 ![image](https://user-images.githubusercontent.com/58063712/267289611-753d7afe-d0e6-4a89-af3b-8eefe05776d1.png)

你环境是什么

**Comment by asyncwhale** [comment]
> > 我大概理解你的意思啦，这个报错你有见过吗 ![image](https://user-images.githubusercontent.com/58063712/267289611-753d7afe-d0e6-4a89-af3b-8eefe05776d1.png)
> 
> 你环境是什么

我是mac的电脑 x86_64

**Comment by MaxKingPor** [comment]
编译环境有问题 clang 无法找到红框的东西
![image](https://github.com/MaxKingPor/libgmssl-sys/assets/43533178/1853e4a9-4264-421d-b354-6dc872994515)

**Comment by asyncwhale** [comment]
okkk，我再研究下看看

**Comment by John-Yu** [comment]
可以看看这个纯rust的库 https://github.com/John-Yu/SM9_core
